# Generated by Django 4.2.6 on 2023-11-14 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vulnerable_project', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InsecureUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
