# Generated by Django 4.2.6 on 2023-11-14 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vulnerable_project', '0002_insecureuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='insecureuser',
            name='user_data',
            field=models.JSONField(default={}),
            preserve_default=False,
        ),
    ]
